var InnerWest = [
  {
    "SA3_Name": "Leichhardt",
    "Year": 2014,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.87051537,
    "Longitude": 151.1679398,
    "New business entries": 995,
    "Average Business Research and Development Expenditure": 25224827,
    "Agriculture, Forestry and Fishing (count of businesses)": 100,
    "Arts and Recreation Services (count of businesses)": 255,
    "Financial and Insurance Services (count of businesses)": 564,
    "Mining (count of businesses)": 6,
    "Professional, Scientific and Technical Services (count of businesses)": 1763
  },
  {
    "SA3_Name": "Leichhardt",
    "Year": 2015,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.87051537,
    "Longitude": 151.1679398,
    "New business entries": "NA",
    "Average Business Research and Development Expenditure": "NA",
    "Agriculture, Forestry and Fishing (count of businesses)": 93,
    "Arts and Recreation Services (count of businesses)": 259,
    "Financial and Insurance Services (count of businesses)": 610,
    "Mining (count of businesses)": 3,
    "Professional, Scientific and Technical Services (count of businesses)": 1799
  },
  {
    "SA3_Name": "Leichhardt",
    "Year": 2013,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.87051537,
    "Longitude": 151.1679398,
    "New business entries": 849,
    "Average Business Research and Development Expenditure": 29941054,
    "Agriculture, Forestry and Fishing (count of businesses)": 100,
    "Arts and Recreation Services (count of businesses)": 283,
    "Financial and Insurance Services (count of businesses)": 536,
    "Mining (count of businesses)": 6,
    "Professional, Scientific and Technical Services (count of businesses)": 1716
  },
  {
    "SA3_Name": "Marrickville - Sydenham - Petersham",
    "Year": 2013,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.91010694,
    "Longitude": 151.1612797,
    "New business entries": 654,
    "Average Business Research and Development Expenditure": 15125559,
    "Agriculture, Forestry and Fishing (count of businesses)": 29,
    "Arts and Recreation Services (count of businesses)": 169,
    "Financial and Insurance Services (count of businesses)": 281,
    "Mining (count of businesses)": 0,
    "Professional, Scientific and Technical Services (count of businesses)": 847
  },
  {
    "SA3_Name": "Marrickville - Sydenham - Petersham",
    "Year": 2015,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.91010694,
    "Longitude": 151.1612797,
    "New business entries": "NA",
    "Average Business Research and Development Expenditure": "NA",
    "Agriculture, Forestry and Fishing (count of businesses)": 29,
    "Arts and Recreation Services (count of businesses)": 160,
    "Financial and Insurance Services (count of businesses)": 344,
    "Mining (count of businesses)": 0,
    "Professional, Scientific and Technical Services (count of businesses)": 945
  },
  {
    "SA3_Name": "Marrickville - Sydenham - Petersham",
    "Year": 2014,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.91010694,
    "Longitude": 151.1612797,
    "New business entries": 843,
    "Average Business Research and Development Expenditure": 16598021,
    "Agriculture, Forestry and Fishing (count of businesses)": 28,
    "Arts and Recreation Services (count of businesses)": 155,
    "Financial and Insurance Services (count of businesses)": 326,
    "Mining (count of businesses)": 3,
    "Professional, Scientific and Technical Services (count of businesses)": 907
  },
  {
    "SA3_Name": "Marrickville - Sydenham - Petersham",
    "Year": 2010,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.91010694,
    "Longitude": 151.1612797,
    "New business entries": 989,
    "Average Business Research and Development Expenditure": 8806560,
    "Agriculture, Forestry and Fishing (count of businesses)": 92,
    "Arts and Recreation Services (count of businesses)": 15,
    "Financial and Insurance Services (count of businesses)": 245,
    "Mining (count of businesses)": 15,
    "Professional, Scientific and Technical Services (count of businesses)": 255
  },
  {
    "SA3_Name": "Marrickville - Sydenham - Petersham",
    "Year": 2011,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.91010694,
    "Longitude": 151.1612797,
    "New business entries": 885,
    "Average Business Research and Development Expenditure": 10545175,
    "Agriculture, Forestry and Fishing (count of businesses)": 39,
    "Arts and Recreation Services (count of businesses)": 187,
    "Financial and Insurance Services (count of businesses)": 260,
    "Mining (count of businesses)": 9,
    "Professional, Scientific and Technical Services (count of businesses)": 861
  },
  {
    "SA3_Name": "Marrickville - Sydenham - Petersham",
    "Year": 2012,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.91010694,
    "Longitude": 151.1612797,
    "New business entries": 896,
    "Average Business Research and Development Expenditure": 16379114,
    "Agriculture, Forestry and Fishing (count of businesses)": 36,
    "Arts and Recreation Services (count of businesses)": 187,
    "Financial and Insurance Services (count of businesses)": 269,
    "Mining (count of businesses)": 3,
    "Professional, Scientific and Technical Services (count of businesses)": 879
  },
  {
    "SA3_Name": "Strathfield - Burwood - Ashfield",
    "Year": 2013,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.88577696,
    "Longitude": 151.10569,
    "New business entries": 2059,
    "Average Business Research and Development Expenditure": 31470828,
    "Agriculture, Forestry and Fishing (count of businesses)": 100,
    "Arts and Recreation Services (count of businesses)": 166,
    "Financial and Insurance Services (count of businesses)": 1008,
    "Mining (count of businesses)": 6,
    "Professional, Scientific and Technical Services (count of businesses)": 1915
  },
  {
    "SA3_Name": "Strathfield - Burwood - Ashfield",
    "Year": 2010,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.88577696,
    "Longitude": 151.10569,
    "New business entries": 3013,
    "Average Business Research and Development Expenditure": 24015377,
    "Agriculture, Forestry and Fishing (count of businesses)": 67,
    "Arts and Recreation Services (count of businesses)": 21,
    "Financial and Insurance Services (count of businesses)": 87,
    "Mining (count of businesses)": 661,
    "Professional, Scientific and Technical Services (count of businesses)": 2474
  },
  {
    "SA3_Name": "Strathfield - Burwood - Ashfield",
    "Year": 2011,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.88577696,
    "Longitude": 151.10569,
    "New business entries": 2552,
    "Average Business Research and Development Expenditure": 49744724,
    "Agriculture, Forestry and Fishing (count of businesses)": 124,
    "Arts and Recreation Services (count of businesses)": 188,
    "Financial and Insurance Services (count of businesses)": 956,
    "Mining (count of businesses)": 9,
    "Professional, Scientific and Technical Services (count of businesses)": 1947
  },
  {
    "SA3_Name": "Strathfield - Burwood - Ashfield",
    "Year": 2012,
    "Remoteness": "Major Cities of Australia",
    "Latitude": -33.88577696,
    "Longitude": 151.10569,
    "New business entries": 2453,
    "Average Business Research and Development Expenditure": 24097511,
    "Agriculture, Forestry and Fishing (count of businesses)": 115,
    "Arts and Recreation Services (count of businesses)": 194,
    "Financial and Insurance Services (count of businesses)": 1023,
    "Mining (count of businesses)": 8,
    "Professional, Scientific and Technical Services (count of businesses)": 1996
  }
]